name: Build Apps

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build-android:
    name: Construir APK de Android
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ERP-POS-PRO
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Release APK
        run: flutter build apk --release --split-per-abi

      - name: Upload Android Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-release-apk
          path: ERP-POS-PRO/build/app/outputs/flutter-apk/*.apk

  build-windows:
    name: Compilar ejecutable de Windows
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./ERP-POS-PRO
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Windows Release
        run: flutter build windows --release

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-release-app
          path: ERP-POS-PRO/build/windows/x64/runner/Release
